### ISSUE TITLE
Unsubscribe action for donors and sponsors

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/lifebank#147]
Dep: #734

As a donor or sponsor I should be able to unsubscribe from my user profile so that I can opt-out of the app
```
ACTION lifebankcode::unsubscribe(name user, eosio::asset community_asset)
{
  require_auth(user);
  check_consent(user);
```

- [x] Check with @xavier506 why lifebanks not included in this issue.
- [x] Check smart contract. @leisterfrancisco 
- [x] Check if the feature is available (it is in smart contracts) 
- [x] Design and front-end for the user interface

**Comment by leisterfrancisco** [comment]
Solved by https://github.com/eoscostarica/lifebank/pull/817
