### ISSUE TITLE
Frontpage redesign

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/lifebank#202]
As a user I want to have enough information on the front page so I can learn what role and where to go so I can continue helping.

US Size: M

Tasks:
- [x] Frontpage design @murillojorge 
- [X] Frontpage coding movile version
- [ ] Frontpage coding Desktop version

Elements:
- Browse (mapbox) in my community.
- Offer posts and Lifebank listings.
- Footer bar tools and FAB

**Comment by ldrojas** [comment]
Frontpage copy:

[20200901 Copy lifebank UX.pdf](https://github.com/eoscostarica/lifebank/files/5233621/20200901.Copy.lifebank.UX.pdf)

**Comment by murillojorge** [comment]
Please refer to Zeplin designs: https://app.zeplin.io/project/5eb9dc41a992ec751f119b88/dashboard?seid=5f6a704bab272704c6baa995

**Comment by murillojorge** [comment]
Let's have two listings: "Offers" and "Lifebanks"
