### ISSUE TITLE
Splash intro component

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/lifebank#246]
As a first time user I want to understand what I'm able to do with Lifebank so I can go ahead and choose my role.

US Size: M

Elements:
- [x] Set of splash intro slides component.
- [x] Splash design
- [x] Splash slides copy
- [x] Splash designs for desktop

**Comment by murillojorge** [comment]
https://app.zeplin.io/project/5eb9dc41a992ec751f119b88/dashboard?seid=5f6a704bab272704c6baa995

**Comment by ldrojas** [comment]
### Copy:

**(1)** Welcome to Lifebank – Donate blood. Save lives.

**(2)** Donors can earn tokens by completing a blood donation at a registered lifebank.

**(3)** Lifebanks are participating centers that gather blood donations and manage tokens.

**(4)** Local businesses can receive tokens in exchange for a promotion, discount, or bonus.
