### ISSUE TITLE
Problem with traductions

### ISSUE THREAD

**Issue by JeanVegaD** [eoscostarica/lifebank#325]
![image](https://user-images.githubusercontent.com/19317138/97454573-8826c700-18fc-11eb-99e7-cf27aeed08bd.png)

**Map popup component**
![image](https://user-images.githubusercontent.com/17890146/97466821-2456cb00-1909-11eb-98da-d02f7aa52e84.png)
**DonationsDashboard.js**

**Comment by AngeloCG97** [comment]
![image](https://user-images.githubusercontent.com/51149817/97455377-67ab3c80-18fd-11eb-8434-f950000d220b.png)

**Comment by JeanVegaD** [comment]
![image](https://user-images.githubusercontent.com/19317138/97486049-88d15480-1920-11eb-9f88-d141a79d081d.png)

Searchbar

**Comment by JeanVegaD** [comment]
![image](https://user-images.githubusercontent.com/19317138/97626457-75d98580-19ef-11eb-9c44-dda9edcf6546.png)

Login

**Comment by JeanVegaD** [comment]
![image](https://user-images.githubusercontent.com/19317138/97631050-074bf600-19f6-11eb-9ff1-06dad2216fbb.png)

add offer
