### ISSUE TITLE
Review useEffect implementations

### ISSUE THREAD

**Issue by JustinCast** [eoscostarica/lifebank#420]
- [x] Search info about React.memo
- [x] Initialize values when component is mounted – see #508  

Own: @Edgar097 
Sup: @steph222

**Comment by Edgar097** [comment]
Use Cases:
- [] Pure Functional Component
- [] Renders Often
- [] Re-renders with the same props **
- [] Medium to big size




![image](https://user-images.githubusercontent.com/76976401/108268562-b3972100-713a-11eb-900a-b007dde4fa39.png)
