### ISSUE TITLE
Add google analytics script

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#493]
Understanding the users to gather data, track users and their navigation across the website, what they are searching for. 

- [x] Create Google Analytics account
- [x] Link account

Use component: React GA - configure property ID

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/118006097-35e14c80-b308-11eb-8b75-3d7b2e633f37.png)

Global site tag (gtag.js) Use this if you're using a website builder or CMS-hosted site
Add the Analytics tag to your website to begin seeing data in your property.
Copy the global site tag into the <head> section of your HTML. Or, if you use a website builder (e.g. WordPress, Shopify, etc), copy the global site tag into your website builder’s custom HTML field.


```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HDWQQ54724"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HDWQQ54724');
</script>
```
