### ISSUE TITLE
The token needs to be reactive

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#497]
Related to: https://github.com/eoscostarica/lifebank/projects/1#card-51684384

Steps to test (Under lifebank and donor profile):

**Sequence**: When a Lifebank transfer tokens to a donor, this should reflect automatically inside the Donor Profile Dashboard.

1. Go to dashboard section
2. See reflected current tokens

Solutions:
1. Use hasura subscription
2. Use blockchain approach with dmobs (make subcriptions). References https://github.com/EOSIO/history-tools

- [x] Database scheme design migrations
- [x] Hasura action for token transfers
- [x] Persist token balance database
- [x] Graphql subscriptions to reflect balance on front-end

**Comment by JustinCast** [comment]
@ldrojas  When a token is minted or transferred to another actor, the token needs to be reflected immediately in the UI (actually it's need to reopen the bottom sheet)
