### ISSUE TITLE
Define list of notifications show in the app

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#544]
- [x] Review the user flow to define what touchpoints require a notification.
- [x] Identify notifications categories.
- [x] Define design per notification categories.

Own: @leisterfrancisco 
Sup: @steph222 
[Lifebank-GeneralFlows.pdf](https://github.com/eoscostarica/lifebank/files/6198521/Lifebank-GeneralFlows.pdf)

**Comment by leisterfrancisco** [comment]
# Notification Category

## Actions
1. Welcome to Lifebank
2. Profile edited correctly

## Token Transaction
1. Offer redeem correctly (donor, sponsor)

## News
1. New offer

## Urgency
1. 

##
