### ISSUE TITLE
Create list of categories for sponsors

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#550]
- A business user must select a category when creating the profile.
- The category is visualized in the business's profile by all the users.

Review: https://schema.org/LocalBusiness

Related to: #559

- [x] Create Busuness List
- [x] Apply

**Comment by steph222** [comment]
Busuness List:

- Auto Repair
- Bar Restaurant
- Beauty Salon
- Construction
- Dentista **
- Dry Cleaning Or Laundry **
- Entertainment Business **
- Financial Professional
- Food Establishment **
- Gym **
- Home Service Professional
- Hospitality
- Laundry or Dry Cleaner
- Manufacturing
- Medical
- Minority-owned business
- Non-Profit Organization
- Real Estate
- Restaurant 
- Retail
- Shopping Center **
- Store **
- Transportation
- Travel Agency **
- Veteran-owned business
- Wholesaler
- Women-owned business
