### ISSUE TITLE
Verify how a donor can choose which token to redeem

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#552]
Chronologically by obtained token?
How to make sure the correct tokens are being redeemed?

- [x] Check how it's working right now
- [x] Define next steps

**Comment by leisterfrancisco** [comment]
### Things to consider
- There are 3 tokens category, Level 1, Level 2 and Level 3
- Issue tokens according to:
  1. From 1 to 3 donations: Level 1 token category
  2. From 3 to 5 donations: Level 2 token category
  3. From 6 onwards donations: Level 3 token category

### Steps to classify a token:
1. Separate each offer tag into a kind of token category
2. Classify what Lifebanks provide certain tokens category according to their offer tag restrictions
3. Assign to an offer a token category label according to offer tag

### Steps to charge an offer:
1. Select minimum amount of needed tokens to redeem an offer

### Task that may arise:
1. Show amount of each token category a user has
2. Modify Smart Contracts to accept tokens category
3. Assign a token category to an offer
4. ...

**Comment by leisterfrancisco** [comment]
### Final idea
Most of the Costa Rican's Lifebank belong to CCSS, so CCSS has its own token representation, then according to this, CCSS is a community
