### ISSUE TITLE
Design edit pages for users

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#566]
- [x] Define new design with @murillojorge 
  - [x] Lifebank
  - [x] Sponsor
  - [x] Donor 
- [x] Apply changes
  - [x] Donor user #696
  - [x] Lifebank user #694
  - [x] Sponsor user #695

**Comment by ldrojas** [comment]
@murillojorge

**Comment by murillojorge** [comment]
Please refer to this frames: https://zpl.io/V1xKPrk
