### ISSUE TITLE
Enable the send email option when user don't receive any confirmation email

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/lifebank#573]
After the sign up process don't receive any confirmation email, the user must be able to request for a send email back again. Also is very important to tell him that the mail could be under the spam section.

- [x] Create content ES & EN @ldrojas 
- [x] Button placement design @murillojorge 
- [x] Create dialog box

Steps to test:
1. Go to sign up section
1. Sign up
1. Request for send email again

Own: @steph222 
Sup: @leisterfrancisco

**Comment by ldrojas** [comment]
EN: "We sent you a confirmation email to your inbox. If you can't find it, please check your spam folder. If you still don't find it, you can [ask for another one]." (link to -ask for another email-)

ES: "Te enviamos un correo de confirmación. Si no lo puedes encontrar, revisa tu carpeta de spam. Si todavía no lo encuentras, puedes [solicitar otro correo]." (link to -ask for another email-)

**Comment by murillojorge** [comment]
We'll use a banner. https://material.io/components/banners#anatomy
Component can be found here: https://zpl.io/awz9z6n

Usemos el texto:
EN: "We sent you a confirmation email to your inbox. If you can't find it, please check your spam folder. If you still don't find it, you can resend it." 

ES: "Te enviamos un correo de confirmación. Si no lo puedes encontrar, revisa tu carpeta de spam. Si todavía no lo encuentras, puedes reenviarlo."

Botón: "Resend", "Reenviar"
