### ISSUE TITLE
Freeze header and tabs when looking at lists in mobile when scrolling

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#574]
- [x] Review and define what pages need fixes
- [x] Apply changes
- [x] Test

Own: @steph222 
Sup: @Edgar097

**Comment by Edgar097** [comment]
I think the problem is in the route "Términos de Uso" , the titles of the contracts should be stick to the navbar as it is in the dashboard. Take a look with a phone perspective
![image](https://user-images.githubusercontent.com/76976401/119053798-ce6c7200-b983-11eb-9751-f46961a4846e.png)
