### ISSUE TITLE
Change textfield component to buttons

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/lifebank#588]
Textfield is use as some kind of action selector but this component is not for that purpose.

- [x] Apply changes.
- [x] Check with @murillojorge appropriate UI for this action.
- [x] Add design changes to component according to conversation with Jorge
   - [x] Remove details
   - [x] Change action for icon "..." 
   - [x] Link filter - details 

Steps to test:
1. Sign in as Sponsor
2. Add an offer
3. Go to Offers Management

![image](https://user-images.githubusercontent.com/28828796/112130800-76d1a600-8b8e-11eb-8c95-1f76a51b2b32.png)

**Comment by steph222** [comment]
![image](https://user-images.githubusercontent.com/31549144/117509895-47ada300-af48-11eb-9828-1bf5077ada8e.png)
