### ISSUE TITLE
Check vulnerabilities when logging in

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#590]
When logging in, the password is not verified by the backend and this may cause security breaches.

- [x] Check if vulnerabilities exist
- [x] Research
- [x] Transfer security logic to backend
- [x] Create missing logic in the backend
- [x] Test 

DON'T MERGE UNTIL:
#607 is solved

**Comment by leisterfrancisco** [comment]
@steph222 @Edgar097 @ldrojas Please, don't merge it until next condition:
1. #607 is solved
2. #608 is solved
