### ISSUE TITLE
A sponsor can choose among different icons to add to  their offers

### ISSUE THREAD

**Issue by Edgar097** [eoscostarica/lifebank#605]
As a sponsor user, I want to choose among a library of -10- different icons to add to an offer I created.
- [x] Define list of icons
- [x] Choose icons to display
- [x] Design and create component to choose icon.
- [x] Apply
- [x] Test
- [x] Add title to icon component "Choose an icon" - "Elije un ícono".

![image](https://user-images.githubusercontent.com/76976401/112695716-2f773e00-8e4a-11eb-803b-848ea08deec9.png)

**Comment by steph222** [comment]
List of icons:

- Discount: LocalOffer, MoneyOff
- Free Products: Style, Widgets, WbIridescent
- Coupons:  Whatshot, Timelapse 
- Benefits:  Storefront
- Badges: TagFaces, Stars

--all : ShoppingBasket, ShoppingCart, ScatterPlot, Restaurant, RestaurantMenu ,  OutdoorGrill, OfflineBolt, LocalDining, FilterVintage
