### ISSUE TITLE
Create settings component

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#624]
- [x] Create settings component
- [x] Changes:
  - [x] "User icon" in the main menu
  - [x] "User icon": username, "setting icon": Settings.
  - [x] Move component down to avoid hiding other elements in the menu.
- [x] Check design component with @murillojorge
- [x] Correct typo "Preferred"
- [ ] Add email settings #768
- [x]  Reduce size of header
- [ ] Subscribe/unsubscribe box #147
- [x] Test

A user must have access to change settings such as:

- Settings:
   - Language
   - Email
   - Password
   - Subscribe/unsubscribe []

Sub/unsub: 
EN: Subscribe to receive automatic emails.
ES: Suscribirse a correos automáticos.

@murillojorge can you help us with a design proposal for these?

A user clicks on their profile icon. A dropdown menu is displayed with a "settings" option to edit their account info.

<img width="512" alt="Captura de Pantalla 2021-05-31 a la(s) 09 19 07" src="https://user-images.githubusercontent.com/29232417/120214118-442cd500-c1f1-11eb-8ef7-a71923596f88.png">

**Comment by leisterfrancisco** [comment]
@murillojorge Telegram has this like setting component. We could hold something like:

1. Name
2. Photo
3. Edit profile (link to edit profile)
4. Notifications (settings)
5. Language
6. FAQ
7. Ask a Question

What you think @murillojorge 

![image](https://user-images.githubusercontent.com/28828796/115255587-a58a6000-a0eb-11eb-9f46-163c3dd421d3.png)
![image](https://user-images.githubusercontent.com/28828796/115255641-b33fe580-a0eb-11eb-88a3-6f8f01c0932b.png)

**Comment by murillojorge** [comment]
Name, password, confirm password, email (unless signed by gmail), profile pic (only for donors).
