### ISSUE TITLE
Email uses capital letters in the text field

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#634]
<img width="563" alt="Captura de Pantalla 2021-04-05 a la(s) 09 31 32" src="https://user-images.githubusercontent.com/29232417/113591888-b74f0c00-95f1-11eb-82da-13d52f3df2bf.png">

**Comment by steph222** [comment]
Other profile problems:
![image](https://user-images.githubusercontent.com/31549144/114937840-9198e280-9dfb-11eb-931b-4246db569350.png)
