### ISSUE TITLE
Redesign password recovery

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#653]
- [x] Content recover password component @ldrojas 
- [ ] Content for email @ldrojas 
- [x] Design recover password component @murillojorge 
- [ ] Design change password component @murillojorge 
- [x] Apply changes
- [ ] Test

Linked to #623

Steps:
1. A user clicks on "forgot password" button.
2. A user is directed to "recover password" component.
3. A user receives an email with a new provisional password.
4. A user must login using this provisional password.

EN: Use your email address registered to Lifebank to recover your password. We’ll send you an email for you to set up a new password.

ES: Use su correo electrónico registrado en Lifebank para recuperar su contraseña. Le enviaremos un correo para que cree una nueva.

**Comment by murillojorge** [comment]
@Edgar097 @ldrojas take a look at this and let me know if I'm missing anything: https://zpl.io/Vk1W418

**Comment by Edgar097** [comment]
> @Edgar097 @ldrojas take a look at this and let me know if I'm missing anything: https://zpl.io/Vk1W418

Looks great, we also need a component so the user can change the password

**Comment by ldrojas** [comment]
EN: Use your email address registered to Lifebank to recover your password. We’ll send you an email for you to set up a new password.

ES: Use su correo electrónico registrado en Lifebank para recuperar su contraseña. Le enviaremos un correo para que cree una nueva.
