### ISSUE TITLE
Create email flows

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#684]
- [x] Write emails content: #498
- [x] Apply emails
  - [x] Lifebanks #698
  - [x] Sponsors #699
  - [x] Donors #700
- [ ] Test email flows #800
  
Content from #498 
### Lifebanks:

- [x] Confirm email
- [x] Welcome to Lifebank and onboarding (email verified)
- [x] Monthly transactions history (CronJob and query) - M
- [x] Weekly new sponsors and offers report (CronJob and query) - M
- [ ] ~~Closing account (Query) - XS~~

### Sponsors:

- [x] Confirm email
- [x] Welcome to Lifebank and onboarding (email verified)
- [x] Monthly transactions history (CronJob and query) - M
- [x] New lifebank nearby (Radius distance) - (Trigger and query) - M
- [ ] ~~Closing account (Query) - XS~~

### Donors:

- [x] Confirm email
- [x] Welcome to Lifebank and onboarding (email verified)
- [x] Send email donation congratulation
- [x] Yearly transactions history
- [x] New lifebank nearby (Radius distance) - (Trigger and query) - M
- [x] Monthly new sponsors and offers report (CronJob and query) - M
- [ ] ~~Closing account (Query) - XS~~

**Comment by leisterfrancisco** [comment]
Solved by https://github.com/eoscostarica/lifebank/pull/727
