### ISSUE TITLE
Review list of sponsor categories

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#685]
<img width="317" alt="Captura de Pantalla 2021-04-19 a la(s) 10 00 40" src="https://user-images.githubusercontent.com/29232417/115267171-1a629780-a0f6-11eb-87de-9ea6cc7725a1.png">

**Comment by xavier506** [comment]
It would be great if we could apply structured data around this also 

https://schema.org/LocalBusiness
