### ISSUE TITLE
A user wants to close an account

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#734]
A user wants to close the account.

Steps:
- A user goes to settings and requests to close the account.
- A user must confirm using the password.
- A user will receive an email confirming the account is closed.
- A user is unsubscribed from emails.
- Data will be stored for 90 days and then will be deleted. 
- A user reopens the account with previous data.

- [x] Front-end #737 - #807
- [x] Backend #738
- [x] Unsubscribe emails #147

**Comment by leisterfrancisco** [comment]
Solved by https://github.com/eoscostarica/lifebank/pull/817
