### ISSUE TITLE
Ideate solution to approve new lifebanks

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#833]
Dep: #832

Governance model? 
DAO?
News to be global.

More in https://ethereum.org/en/dao/

Check it out:
- EOSIO Multisign
- eosio.msig

**Comment by leisterfrancisco** [comment]
### Proposal
- First Lifebank is gonna be monitored by us
- 1/3 to accept a new Lifebank

#### Smart Contract
- Each preregister Lifebank record is gonna have the pre-register lifebank name, and the lifebank that vote to accept a new one.

#### Backend
- A cronjob that check each day if exist a new Preregister Lifebank to accept. Basically the main idea is to create a cronjob that communicate with the blockchain to check if exist a Lifebank that can be accepted. Itself make a request to blockchain to check if exist a new possible Lifebank and in case of can be accepted, register the transaction id in the database and make that pre-register Lifebank visible in the platform.

**Comment by xavier506** [comment]
Check out the EOSIO multisig contracts

https://developers.eos.io/manuals/eosio.contracts/latest/guides/how-to-sign-a-multisig-transaction-with-eosio.msig
